version: '3.7'

services:
  db:
    image: postgres:14-alpine

    volumes:
      - ~/dbs/javaTablut/data:/var/lib/postgresql/data

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Student_1234
      POSTGRES_DATABASE: int_tablut

    ports:
      - "5432:5432"